[package]
name = "myriam"
version = "0.0.2"
edition = "2021"
license = "Apache-2.0"
description = "Remote actors with e2e encryption."
homepage = "https://gitlab.com/ariSun/myriam-rs"
repository = "https://gitlab.com/ariSun/myriam-rs"
categories = ["concurrency", "network-programming", "asynchronous"]
keywords = ["actor", "actors", "distributed"]
authors = ["Ariela Wenner <arisunz at disroot dot org>"]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
async-trait = "0.1.53"
bincode = "1.3.3"
chrono = "0.4.19"
crypto_box = { version = "0.7.2", features = ["std", "serde"] }
serde = { version = "1.0.136", features = ["derive"] }
sha256 = "1.0.3"
thiserror = "1.0.30"
tokio = { version = "1.17.0", features = ["full"] }
tracing = "0.1.34"

[dev-dependencies]
tracing-subscriber = { version = "0.3.11", features = ["env-filter"] }
