[package]
name = "myriam"
version = "0.0.10"
edition = "2021"
license = "Apache-2.0"
description = "Remote actors on top of libp2p."
homepage = "https://codeberg.org/arisunz/myriam-rs"
repository = "https://codeberg.org/arisunz/myriam-rs"
categories = ["concurrency", "network-programming", "asynchronous"]
keywords = ["actor", "actors", "distributed", "libp2p"]
authors = ["Ariela Wenner <arisunz at disroot dot org>"]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]

[dev-dependencies]

[profile.bench]
debug = true
