[package]
name = "myriam"
version = "0.0.7"
edition = "2021"
license = "Apache-2.0"
description = "Remote actors on top of libp2p."
homepage = "https://codeberg.org/arisunz/myriam-rs"
repository = "https://codeberg.org/arisunz/myriam-rs"
categories = ["concurrency", "network-programming", "asynchronous"]
keywords = ["actor", "actors", "distributed", "libp2p"]
authors = ["Ariela Wenner <arisunz at disroot dot org>"]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
async-trait = "0.1.57"
bincode = "1.3.3"
libp2p = { version = "0.49.0", features = ["serde", "request-response", "kad", "noise", "yamux", "websocket", "mplex", "tcp", "mdns", "dns", "tokio"] }
serde = { version = "1.0.145", features = ["derive"] }
thiserror = "1.0.37"
tokio = { version = "1.21.2", features = ["full"] }
tracing = "0.1.37"

[dev-dependencies]
tracing-subscriber = { version = "0.3.16", features = ["env-filter"] }

[profile.bench]
debug = true
