[package]
name = "chatapp"
version = "0.1.0"
edition = "2021"

[dependencies]
color-eyre = "0.6.3"
myriam = { path = "../../", version = "0.0.13" }
ratatui = "0.27.0"
serde = { version = "1.0.204", features = ["derive"] }
thiserror = "1.0.63"
tokio = { version = "1.38.1", features = ["full"] }
